name: Publish Docker Image

on:
  push:
    tags:
      - 'v*' # Ejecuta el flujo cuando se crea un tag que comienza con "v" (por ejemplo, v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/springboot-app:${{ github.sha }} .
        
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}

      - name: Tag image with release version
        run: |
          docker tag ${{ vars.DOCKER_USERNAME }}/springboot-app:${{ github.sha }} ${{ vars.DOCKER_USERNAME }}/springboot-app:${{ github.ref_name }}

      - name: Push the release version image to Docker Hub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/springboot-app:${{ github.ref_name }}